//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class announcement
    {
        public int ID_announcement { get; set; }
        public string topic { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> announceTime { get; set; }
        public string status { get; set; }
    }
}
